#!/bin/bash

bash-it enable alias docker
bash-it enable alias fuck
bash-it enable alias npm
bash-it enable alias rails
bash-it enable alias vim
bash-it enable plugin git
bash-it enable completion bash-it
bash-it enable completion bundler
bash-it enable completion docker
bash-it enable completion flutter
bash-it enable completion gem
bash-it enable completion git
bash-it enable completion helm
bash-it enable completion npm
bash-it enable completion nvm
bash-it enable completion rake
bash-it enable completion system
