local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.grep_string, {})
vim.keymap.set('n', '<leader>fr', builtin.registers, {})
vim.keymap.set('n', '<leader>fs', builtin.live_grep, {})
vim.keymap.set('n', '<C-p>', builtin.find_files, {})
vim.keymap.set('n', '<C-G>', builtin.buffers, {})
