#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
REL_PATH="`dirname \"$0\"`"
RUBY_VERSION=`cat $REL_PATH/../../.ruby-version`
PART_VERSION=`echo $RUBY_VERSION | awk 'BEGIN { FS = "-" } ; { print $1 }'`
GEMDIR=/opt/boxen/rbenv/versions/$RUBY_VERSION/lib/ruby/gems/$PART_VERSION/gems/
echo $GEMDIR
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=-javascript,sql --exclude=log --exclude=angular/node_modules --exclude=*bower_components* --exclude=syntastic.log --exclude=doc --exclude=nohup.out --exclude=coverage --exclude=prototype --exclude=*coffee-script-source* --exclude=tmp --exclude=features --exclude=spec * $GEMDIR
mv .git/tags.$$ .git/tags

