#!/usr/local/opt/coreutils/libexec/gnubin/env ruby

diff = %x{git diff --cached | egrep -v "config.filter_run focus: true"}
if diff =~ / focus: true/
  puts "Don't check in focus: true for any specs, aborting"
  exit 1
end
