#!/usr/local/opt/coreutils/libexec/gnubin/env ruby

diff = `git diff --cached | grep -E -v "config.filter_run focus: true"`
if diff =~ / focus: true/
  puts "Don't check in focus: true for any specs, aborting"
  exit 1
end
